/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Camera Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getCameraOperation()
 * @model
 * @generated
 */
public interface CameraOperation extends Operation
{
} // CameraOperation
