/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.ColorValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getColorValue()
 * @model
 * @generated
 */
public interface ColorValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLang.factoryLang.COLOR}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see xtext.factoryLang.factoryLang.COLOR
   * @see #setValue(COLOR)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getColorValue_Value()
   * @model
   * @generated
   */
  COLOR getValue();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.ColorValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see xtext.factoryLang.factoryLang.COLOR
   * @see #getValue()
   * @generated
   */
  void setValue(COLOR value);

} // ColorValue
