/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.Configuration#getDevice <em>Device</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Device</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device</em>' containment reference.
   * @see #setDevice(Device)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getConfiguration_Device()
   * @model containment="true"
   * @generated
   */
  Device getDevice();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.Configuration#getDevice <em>Device</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device</em>' containment reference.
   * @see #getDevice()
   * @generated
   */
  void setDevice(Device value);

} // Configuration
