/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crane Position Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.CranePositionParameter#getDegree <em>Degree</em>}</li>
 *   <li>{@link xtext.factoryLang.factoryLang.CranePositionParameter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getCranePositionParameter()
 * @model
 * @generated
 */
public interface CranePositionParameter extends CraneParameter
{
  /**
   * Returns the value of the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degree</em>' attribute.
   * @see #setDegree(int)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getCranePositionParameter_Degree()
   * @model
   * @generated
   */
  int getDegree();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.CranePositionParameter#getDegree <em>Degree</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degree</em>' attribute.
   * @see #getDegree()
   * @generated
   */
  void setDegree(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getCranePositionParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.CranePositionParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // CranePositionParameter
