/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crane Pickup Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getCranePickupOperation()
 * @model
 * @generated
 */
public interface CranePickupOperation extends CraneOperation
{
} // CranePickupOperation
