/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk Wait Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskWaitOperation()
 * @model
 * @generated
 */
public interface DiskWaitOperation extends DiskOperation
{
} // DiskWaitOperation
