/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk Move Empty Slot Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskMoveEmptySlotOperation#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMoveEmptySlotOperation()
 * @model
 * @generated
 */
public interface DiskMoveEmptySlotOperation extends DiskOperation
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(DiskZoneParameter)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMoveEmptySlotOperation_Target()
   * @model
   * @generated
   */
  DiskZoneParameter getTarget();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskMoveEmptySlotOperation#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(DiskZoneParameter value);

} // DiskMoveEmptySlotOperation
