/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk State Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskStateValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskStateValue()
 * @model
 * @generated
 */
public interface DiskStateValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLang.factoryLang.DISK_STATES}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see xtext.factoryLang.factoryLang.DISK_STATES
   * @see #setValue(DISK_STATES)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskStateValue_Value()
   * @model
   * @generated
   */
  DISK_STATES getValue();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskStateValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see xtext.factoryLang.factoryLang.DISK_STATES
   * @see #getValue()
   * @generated
   */
  void setValue(DISK_STATES value);

} // DiskStateValue
