/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.Disk#getSlotParameter <em>Slot Parameter</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDisk()
 * @model
 * @generated
 */
public interface Disk extends Device
{
  /**
   * Returns the value of the '<em><b>Slot Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slot Parameter</em>' containment reference.
   * @see #setSlotParameter(DiskParameter)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDisk_SlotParameter()
   * @model containment="true"
   * @generated
   */
  DiskParameter getSlotParameter();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.Disk#getSlotParameter <em>Slot Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slot Parameter</em>' containment reference.
   * @see #getSlotParameter()
   * @generated
   */
  void setSlotParameter(DiskParameter value);

} // Disk
