/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk Mark Slot Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getTarget <em>Target</em>}</li>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getDiskSlotValue <em>Disk Slot Value</em>}</li>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getMeasure <em>Measure</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMarkSlotOperation()
 * @model
 * @generated
 */
public interface DiskMarkSlotOperation extends DiskOperation
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(DiskZoneParameter)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMarkSlotOperation_Target()
   * @model
   * @generated
   */
  DiskZoneParameter getTarget();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(DiskZoneParameter value);

  /**
   * Returns the value of the '<em><b>Disk Slot Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disk Slot Value</em>' containment reference.
   * @see #setDiskSlotValue(DiskSlotValue)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMarkSlotOperation_DiskSlotValue()
   * @model containment="true"
   * @generated
   */
  DiskSlotValue getDiskSlotValue();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getDiskSlotValue <em>Disk Slot Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disk Slot Value</em>' containment reference.
   * @see #getDiskSlotValue()
   * @generated
   */
  void setDiskSlotValue(DiskSlotValue value);

  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMarkSlotOperation_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Measure</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLang.factoryLang.TIME}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Measure</em>' attribute.
   * @see xtext.factoryLang.factoryLang.TIME
   * @see #setMeasure(TIME)
   * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getDiskMarkSlotOperation_Measure()
   * @model
   * @generated
   */
  TIME getMeasure();

  /**
   * Sets the value of the '{@link xtext.factoryLang.factoryLang.DiskMarkSlotOperation#getMeasure <em>Measure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Measure</em>' attribute.
   * @see xtext.factoryLang.factoryLang.TIME
   * @see #getMeasure()
   * @generated
   */
  void setMeasure(TIME value);

} // DiskMarkSlotOperation
