/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getLocalVariable()
 * @model
 * @generated
 */
public interface LocalVariable extends Variable
{
} // LocalVariable
