/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.factoryLang.FactoryLangPackage#getLoop()
 * @model
 * @generated
 */
public interface Loop extends Statement
{
} // Loop
