/*
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link FactoryLangWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractFactoryLangWebModule extends DefaultWebModule {

}
