/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.factoryLang.factoryLang.CameraOperation;
import xtext.factoryLang.factoryLang.FactoryLangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Camera Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CameraOperationImpl extends OperationImpl implements CameraOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CameraOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FactoryLangPackage.Literals.CAMERA_OPERATION;
  }

} //CameraOperationImpl
