/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.factoryLang.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.factoryLang.factoryLang.CraneDropOperation;
import xtext.factoryLang.factoryLang.FactoryLangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Crane Drop Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CraneDropOperationImpl extends CraneOperationImpl implements CraneDropOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CraneDropOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FactoryLangPackage.Literals.CRANE_DROP_OPERATION;
  }

} //CraneDropOperationImpl
