/*
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFactoryLangScopeProvider extends DelegatingScopeProvider {
}
