/*
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtext.factoryLang.ui.internal.FactoryLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FactoryLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FactoryLangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FactoryLangActivator activator = FactoryLangActivator.getInstance();
		return activator != null ? activator.getInjector(FactoryLangActivator.XTEXT_FACTORYLANG_FACTORYLANG) : null;
	}

}
