/**
 * generated by Xtext 2.26.0
 */
package xtext.factoryLang.web;

import com.google.inject.Binder;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.web.server.XtextServiceDispatcher;
import org.eclipse.xtext.web.server.model.IWebResourceSetProvider;
import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import org.eclipse.xtext.web.server.validation.ValidationService;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FactoryLangWebModule extends AbstractFactoryLangWebModule {
  private final IResourceBaseProvider resourceBaseProvider;
  
  public Class<? extends IWebResourceSetProvider> bindIWebResourceSetProvider() {
    return FactoryLangResourceSetProvider.class;
  }
  
  public void configureResourceBaseProvider(final Binder binder) {
    if ((this.resourceBaseProvider != null)) {
      binder.<IResourceBaseProvider>bind(IResourceBaseProvider.class).toInstance(this.resourceBaseProvider);
    }
    binder.<ValidationService>bind(ValidationService.class).to(FactoryLangValidationService.class);
  }
  
  public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
    return FileResourceHandler.class;
  }
  
  public Class<? extends XtextServiceDispatcher> bindXtextServiceDispatcher() {
    return FactoryLangServiceDispatcher.class;
  }
  
  public FactoryLangWebModule(final IResourceBaseProvider resourceBaseProvider) {
    super();
    this.resourceBaseProvider = resourceBaseProvider;
  }
}
